name: t3_hashviz
description: A library for generating a visualization blocks from a hash (commonly known as Identicons).
version: 0.1.0-dev
homepage: http://t3infosecurity.com/

environment:
  sdk: ^3.4.0

dependencies:
  hashlib: ^1.16.0
  fixnum: ^1.1.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
