name: hashviz
description: One of the Greatwall TKBA protocol implementations. It returns different types of hash visualization (commonly referred to as Identicons) for given hashes.
version: 1.0.0
homepage: http://t3infosecurity.com/

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0