import 'package:fixnum/fixnum.dart';

import 'utils.dart';

/// A Hash visualization class from a provided hash as blocks of pixels.
class Hashviz {
  String hashToVisualize;
  int visualizationSize;
  List<int> _randomSeed = [];

  /// Create a visualization hash class.
  ///
  /// Depending on provided [hashToVisualize] and [visualizationSize] a
  /// visualization blocks will be generated. [hashToVisualize] is the string
  /// to be represented as visualization blocks. [visualizationSize]
  /// represents the blocks size in the visualization, if it is negative only
  /// the absolute value will be considered.
  Hashviz({
    required this.hashToVisualize,
    int visualizationSize = 10,
  }) : visualizationSize =
            isValidSize(visualizationSize) ? visualizationSize : 1;

  /// A 2D-array of visualization blocks (image data).
  ///
  /// The visualization blocks (image data) is generated by creating pixels
  /// based on the [Hashviz.hashToVisualize] string. Returns a List of
  /// integers representing the visualization blocks (image data).
  List<int> get visualizationBlocks {
    _randomSeed = _createRandomSeed(hashToVisualize);

    return _createVisualizationBlocks(visualizationSize);
  }

  /// Creates image data.
  ///
  /// The array generated represents the pattern to be drawn. A value of 1 or
  /// 2 means a block should be drawn, while 0 indicates the background.
  ///
  /// For now, only a square images are supported.
  List<int> _createVisualizationBlocks(int visualizationSize) {
    final width = visualizationSize;
    final height = visualizationSize;

    final dataWidth = (width / 2).ceil();
    final mirrorWidth = width - dataWidth;

    var blocks = <int>[];
    for (var y = 0; y < height; y++) {
      var row = <int>[];
      for (var x = 0; x < dataWidth; x++) {
        // this makes foreground and background color to have a 43% (1/2.3)
        // probability spot color has 13% chance
        row.add((_generateRandomFloatFromSeed() * 2.3).floor());
      }
      final r = row.sublist(0, mirrorWidth).toList();
      row.addAll(r.reversed.toList());

      for (var i = 0; i < row.length; i++) {
        blocks.add(row[i]);
      }
    }

    return blocks;
  }

  /// Create random seed from the [seed]
  ///
  /// The [seed] is used to generate consistent patterns.
  List<int> _createRandomSeed(String seed) {
    var randomSeed = List<int>.filled(4, 0);

    for (int i = 0; i < seed.length; i++) {
      randomSeed[i % 4] =
          (randomSeed[i % 4] << 5) - randomSeed[i % 4] + seed.codeUnitAt(i);
    }

    return randomSeed;
  }

  /// Generates a random value based on the seed
  double _generateRandomFloatFromSeed() {
    // based on Java's String.hashCode(), expanded to 4 32bit values
    final t = Int32(_randomSeed[0] ^ Int32(_randomSeed[0] << 11).toInt());
    final third = Int32(_randomSeed[3]);

    _randomSeed[0] = _randomSeed[1];
    _randomSeed[1] = _randomSeed[2];
    _randomSeed[2] = _randomSeed[3];
    _randomSeed[3] = ((third ^ (third >> 19)) ^ t ^ (t >> 8)).toInt();

    return (Int32(_randomSeed[3] >>> 0)).toInt() / ((1 << 31) >>> 0);
  }
}
